### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by bgman111111** [naodsw/kernel_msm-4.9#1]
Hi I make latest TWRP 3.6.2_11 but it don't mtp, sscard fstab don't work. Let's united and help other poor people's be rich. https://forum.xda-developers.com/t/recovery-rmx1971-unofficial-twrp-3-6-2_11-for-realme-5-pro-realme-by-peturbg.4475539/

**Comment by naodsw** [comment]
> Hi I make latest TWRP 3.6.2_11 but it don't mtp, sscard fstab don't work. Let's united and help other poor people's be rich. https://forum.xda-developers.com/t/recovery-rmx1971-unofficial-twrp-3-6-2_11-for-realme-5-pro-realme-by-peturbg.4475539/

For MicroSD and USB OTG support, make sure you've added the block devices for both on the recovery fstab. For further discussion please use the Telegram group or personally DM me (@naodsw) as this isn't really related to the kernel. :)
